### ISSUE TITLE
Resonite Support

### ISSUE THREAD

**Issue by troyBORG** [dfgHiatus/CacheGetClapped#4]
I would like the mod updated so that is supports Resonite

**Comment by dfgHiatus** [comment]
Started work on this! I've pushed the code, feel free to clone it and try it yourself or I can upload a prerelease

**Comment by troyBORG** [comment]
Yeah I don't know how to build this so can you push it as built?

**Comment by dfgHiatus** [comment]
Here is a pre-release build: [CacheGetClapped.zip](https://github.com/dfgHiatus/CacheGetClapped/files/12804942/CacheGetClapped.zip)

**Comment by dfgHiatus** [comment]
Added support for Resonite!
